### ISSUE TITLE
Lawyer contributions

### ISSUE THREAD

**Issue by hshadab** [accordproject/cicero-template-library#133]
Lawyers would like to contribute to this library. In order of importance, lawyers would like to:

1. contribute representative template clause and contract text
2.  contribute parameterized template grammar
3. contribute template models
4.  write and contribute Ergo logic
5.  see a template 'in action' somehow

**Comment by dselman** [comment]
@jeromesimeon good source of requirements for Template Studio.

**Comment by mttrbrts** [comment]
All of the above drafting issues are addressed at https://studio.accordproject.org

We do still need some good instructions on how to use GitHub to share the contribution, however.

**Comment by jeromesimeon** [comment]
Does the studio really support all of those requirements? What if a lawyer wanted to contribute only the text, would that work with the current Cicero implementation?

**Comment by jeromesimeon** [comment]
Can we consider this closed: there is an issue on template studio to track the requirement for templates without logic.
