### ISSUE TITLE
Old versions of templates don't show new versions

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-template-library#144]
https://templates.accordproject.org/acceptance-of-delivery@0.4.0.html

I noticed old versions of templates don’t show newer versions in their versions drop down menu. I wonder if that’s something we should update, so all templates shows every version in its versions dropdown menu. If someone is linked to an old version, there may be no way for them to know there’s a newer version.

![image](https://user-images.githubusercontent.com/40569793/47724060-45a65300-dc2c-11e8-94b2-cdb454613b57.png)

**Comment by dselman** [comment]
This is because the site is 100% static at the moment, so the "old" pages don't know about the newer templates. We probably need to move to some sort of database and REST API to do this properly.

**Comment by jeromesimeon** [comment]
Assigning this to @utajum so people are aware of the PR on this.

**Comment by jeromesimeon** [comment]
I think we need a review on this issue:
- We have two PRs in which add a new target to update the dropdowns (#276 and #287 )
- Does it resolve the issue?
- Can we document the new build process/lifecycle so everyone know what to do on future changes?

**Comment by mttrbrts** [comment]
All done: 
https://github.com/accordproject/cicero-template-library/blob/master/README.md#building-static-pages
