### ISSUE TITLE
Remove Language column from main page

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero-template-library#166]
All templates are now migrated to Ergo, and we plan and deprecate source templates using JavaScript, so the corresponding language column in the index on the main page seem superfluous.

<img width="1198" alt="screen shot 2018-12-07 at 2 31 16 pm" src="https://user-images.githubusercontent.com/670099/49668691-edcde980-fa2c-11e8-97ab-7c2f307d9a31.png">

**Comment by RanadeepPolavarapu** [comment]
I can take this.

**Comment by RanadeepPolavarapu** [comment]
I believe this one seems to be already resolved. The column no longer appears.

**Comment by irmerk** [comment]
> I believe this one seems to be already resolved. The column no longer appears.

Ah it looks like you're right. I should have looked into it before marking it Hacktoberfest. @jeromesimeon I'll close this issue.
