### ISSUE TITLE
Fragile goods. Empty accelerometer readings array causes error

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero-template-library#17]
```
Cannot read property 'forEach' of undefined
```

Need to perform an empty check here or use alternative to forEach.
https://github.com/accordproject/cicero-template-library/blob/326a58670c982fab699e23844ec10952065c848d/fragile-goods/lib/logic.js#L36

**Comment by jeromesimeon** [comment]
This seems to have been fixed in the switch to Ergo: ```bash-3.2$ cicero execute --request request.json 
15:56:33 - info: Logging initialized. 2018-06-22T19:56:33.791Z
15:56:34 - info: Using current directory as template folder
15:56:34 - info: Loading a default sample.txt file.
15:56:34 - info: Loading a default state.json file.
15:56:35 - info: {"clause":"fragile-goods@0.2.0-0eea79d5513163e5beb03d0a98aecb951372dad2e2e232f3bdb28fc7c8f69c0b","request":{"$class":"io.clause.demo.fragileGoods.DeliveryUpdate","startTime":"January 1, 2018 16:34:00","finishTime":"January 1, 2018 16:34:11","status":"ARRIVED","accelerometerReadings":[0.2,0.6,-0.3,-0.7,0.1]},"response":{"$class":"io.clause.demo.fragileGoods.PayOut","amount":{"$class":"org.accordproject.money.MonetaryAmount","doubleValue":790,"currencyCode":"USD"},"transactionId":"60700e2d-d9db-419b-8748-30138d3c7405","timestamp":"2018-06-22T19:56:35.181Z"},"state":{"$class":"org.accordproject.cicero.contract.AccordContractState","stateId":"org.accordproject.cicero.contract.AccordContractState#1"},"emit":[]}
bash-3.2$ cicero execute --request request-empty.json 
15:56:43 - info: Logging initialized. 2018-06-22T19:56:43.532Z
15:56:44 - info: Using current directory as template folder
15:56:44 - info: Loading a default sample.txt file.
15:56:44 - info: Loading a default state.json file.
15:56:44 - info: {"clause":"fragile-goods@0.2.0-bcb0c557c772213426bc59d4ac05640a0959b9352ff72d7974c80c057e7d139c","request":{"$class":"io.clause.demo.fragileGoods.DeliveryUpdate","startTime":"January 1, 2018 16:34:00","finishTime":"January 1, 2018 16:34:11","status":"ARRIVED","accelerometerReadings":[]},"response":{"$class":"io.clause.demo.fragileGoods.PayOut","amount":{"$class":"org.accordproject.money.MonetaryAmount","doubleValue":800,"currencyCode":"USD"},"transactionId":"a00b5558-a62b-4e17-a368-01cb713e0a3c","timestamp":"2018-06-22T19:56:44.937Z"},"state":{"$class":"org.accordproject.cicero.contract.AccordContractState","stateId":"org.accordproject.cicero.contract.AccordContractState#1"},"emit":[]}
```

**Comment by jeromesimeon** [comment]
Added a test in PR #77. Closing this issue.
