### ISSUE TITLE
Migrate template tests to new Cucumber-Gherkin syntax

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero-template-library#180]
Cicero now has support for https://cucumber.io for testing templates. This means we can start migrating templates to that new syntax.

Current work migrating templates is on the following branch: https://github.com/accordproject/cicero-template-library/tree/js-feature-cucumber

Here is the list of templates to be migrated:
- [x] acceptance-of-delivery (@jeromesimeon)
- [x] car-rental-tr (@dselman)
- [x] copyright-license (@dselman)
- [x] demandforecast (@dselman)
- [x] docusign-connect (@dselman)
- [x] eat-apples (@adriaan-pelzer)
- [x] empty (@adriaan-pelzer)
- [x] empty-contract (@adriaan-pelzer)
- [x] fragile-goods (@adriaan-pelzer)
- [x] full-payment-upon-demand (@irmerk)
- [x] full-payment-upon-signature (@petrgazarov)
- [x] hellomodule (@irmerk)
- [x] helloworld (@jeromesimeon)
- [x] helloworldstate (@irmerk)
- [x] installment-sale (@jeromesimeon)
- [x] interest-rate-swap(@DianaLease)
- [x] ip-payment (@irmerk)
- [x] latedeliveryandpenalty (@jeromesimeon)
- [x] lateinvoicewithpayment (@irmerk)
- [x] one-time-payment-tr (@irmerk)
- [x] online-payment-contract-tr (@irmerk)
- [x] payment-upon-delivery(@DianaLease)
- [x] payment-upon-iot (@zacklev)
- [x] payment-upon-signature(@DianaLease)
- [x] perishable-goods (@mttrbrts )
- [x] promissory-note(@DianaLease)
- [x] saft (@Michael-Grover-C)
- [x] safte (@irmerk)
- [x] sales-contract-ru (@irmerk)
- [x] servicelevelagreement (@mttrbrts)
- [x] simplelatedeliveryandpenalty (@jeromesimeon)
- [x] supplyagreement (@irmerk)
- [x] supplyagreement-perishable-goods (@mttrbrts)
- [x] volumediscount (@mttrbrts)

**Comment by jeromesimeon** [comment]
Instructions to migrate:

1. Look at one of the already migrated templates (e.g., `src/acceptance-of-delivery`)

2. Move the file `.cucumber.js` in that template to the one you're working on

3. in the `package.json` for the template you're working on replace:
```
    "devDependencies": {
        "mocha": "5.2.0"
    },
    "scripts": {
        "test": "mocha --timeout 10000"
    }
```
by
```
    "devDependencies": {
        "cucumber": "^5.1.0"
    },
    "scripts": {
        "test": "cucumber-js test -r .cucumber.js"
    }
```

4. in the root of the repo (`cicero-template-library`) run: `lerna bootstrap`

5. Look at the existing tests in `test/logic.js` in the template you are working on, and create a new file `test/logic.feature` for it which covers at least the existing tests

If you need help with syntax, you can take inspiration from any of the already migrated templates. If your template has state, you can find the syntax in the `installment-sale` template.

**Comment by adriaan-pelzer** [comment]
@jeromesimeon What does the `lerna bootstrap` step above do? 
Is it necessary if you use `npm run test` in step 6, and not `lerna run test`?

**Comment by jeromesimeon** [comment]
All tests have been migrated. Thanks to all the contributions! @adriaan-pelzer @DianaLease @dselman @Michael-Grover-C @irmerk @ZackLev @mttrbrts @petrgazarov ! Closing this issue.
