### ISSUE TITLE
latedeliveryandpenalty contract ignoring deliveredAt

### ISSUE THREAD

**Issue by niallroche** [accordproject/cicero-template-library#233]
the current version of the latedeliveryandpenalty clause compares the delivery date against the current date and time, where previously it was checked against the 'deliveredAt' date and time. Perhaps the logic could be improved to check for the presence of deliveredAt and only use the current time if it is there is no deliveredAt specified

**Comment by mttrbrts** [comment]
Thanks @niallroche, I'll review this next week.

**Comment by mttrbrts** [comment]
Hi @niallroche, 

It seems that there are two variants of the late delivery template that have different behaviours:
1. [minilatedeliveryandpenalty](https://github.com/accordproject/cicero-template-library/blob/master/src/minilatedeliveryandpenalty/lib/logic.ergo) - This template requires a request with a `deliveredAt` attribute that is used in the logic
2. [latedeliveryandpenalty](https://github.com/accordproject/cicero-template-library/blob/master/src/latedeliveryandpenalty/lib/logic.ergo) - This template uses the current time instead

IMO, I think that it would be confusing for this template to behave differently depending on the presence of optional fields in the request.

As far as I can tell neither template has switched behaviour, the `minilatedeliveryandpenalty` template was released more recently as part of updates to our documentation.

I hope that this helps?

**Comment by kanav-raina** [comment]
Hi @irmerk
I would like to work on this. Kindly guide me how to solve this issue.

**Comment by irmerk** [comment]
Unsure what to add to what Matt has already said in this issue. Seems this is a non issue.
