### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#253]
**Describe the bug**
Links are broken in the `README`. Some examples:

- [Code of Conduct](https://github.com/accordproject/cicero-template-library/blob/master/CONTRIBUTING.md#contributing-to-cicero-template-library)
- [Cicero Slack Channel](https://github.com/accordproject/cicero-template-library/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
- [core development documentation](https://github.com/accordproject/cicero-template-library/blob/master/CONTRIBUTING.md#-missing-a-feature)
- [Commit Message Guidelines](https://github.com/accordproject/cicero-template-library/blob/master/CONTRIBUTING.md#-want-a-doc-fix)
- [many others...](https://github.com/accordproject/cicero-template-library/blob/master/CONTRIBUTING.md#-pull-request-submission-guidelines)

**Additional context**
Note that the code of conduct should link [here](https://lfprojects.org/policies/code-of-conduct/).

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by RanadeepPolavarapu** [comment]
I'll take a crack at this.
