### ISSUE TITLE
installment-sale template monetary value 

### ISSUE THREAD

**Issue by 4katie** [accordproject/cicero-template-library#254]
**Is your feature request related to a problem? Please describe.**
The current template for 'installment-sale 0.13.0' uses "total amount e[{INITIAL_DUE}]" or "remaining balance of E[{TOTAL_DUE_BEFORE_CLOSING}]". 

**Describe the solution you'd like**
instead of E, it would be nice to have a currency (EUR, GBP) or a currency symbol. 

**Describe alternatives you've considered**
It may be possible to manually amend the text of the template every time you use it... 

**Additional context**

**Comment by jeromesimeon** [comment]
Completed in #255
