### ISSUE TITLE
Update Markdown Files

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#257]
## Tasks
- Take another pass through the templates
  - Ensure `.md` files have markdown
  - Also ensure the markdown is correct and tests pass

## Related Issues:
- N/A

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by sameshl** [comment]
@irmerk Even I would love to work on this. Could you elaborate on how I could go about testing the readme files?

**Comment by irmerk** [comment]
Great @sameshl. @michizhou is already working on this, perhaps you can work together or provide tips? I would be looking into the already existing documentation for `cicero-template-library` and current docs/release notes for the new `0.20-alpha` release to piece this together.

**Comment by michizhou** [comment]
@irmerk I deeply apologize for not updating you on my progress for this issue. I have been working on this, and should be able to get the documentation ready for review by later today. If you could reassign this issue to me, I would greatly appreciate it. Thank you.

**Comment by irmerk** [comment]
@michizhou super job on the consistency and thoroughness on all those PRs, thank you kindly!

I think I'm going to make a new issue, because I realized after looking at this issue again that I did not do a great job at explaining the issue here because this was originally aimed at the markdown files within the new `v0.20` branch (https://github.com/accordproject/cicero-template-library/blob/js-release-0.20/src/acceptance-of-delivery/grammar/template.tem.md as an example)

**Comment by irmerk** [comment]
Created the new issue in #284

This issue will close with #280
