### ISSUE TITLE
minilatedeliveryandpenalty: Buyer and Seller should be swapped

### ISSUE THREAD

**Issue by 4katie** [accordproject/cicero-template-library#259]
**Is your feature request related to a problem? Please describe.**
`[{buyer}] shall pay to [{seller}] a penalty` -- the two placeholders should be swapped

**Describe the solution you'd like**
Template text should be fixed so that seller pays buyer a penalty

**Describe alternatives you've considered**
N/A

**Additional context**
Similar problem with `minilatedeliveryandpenalty-payment`, `minilatedeliveryandpenalty-capped`,  	`simplelatedeliveryandpenalty` templates

**Comment by Frozenaught** [comment]
Hi, I would like to help with this if it is still open.

**Comment by irmerk** [comment]
> Hi, I would like to help with this if it is still open.

Sure thing @Frozenaught, go for it!
