### ISSUE TITLE
Update v0.20 Markdown Files

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#284]
## Tasks
- Take another pass through the templates in the [`js-release-0.20`](https://github.com/accordproject/cicero-template-library/tree/js-release-0.20) branch
  - _Note_: This branch may be merged to master by the time you're reading this
  - _Example_: [`acceptance-of-delivery/grammar/template.tem.md`](https://github.com/accordproject/cicero-template-library/blob/js-release-0.20/src/acceptance-of-delivery/grammar/template.tem.md)
- Ensure `.md` files have markdown
- Also ensure the markdown is correct and tests pass

## Related Issues:
- N/A

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by lkcbharath** [comment]
Hello! Can I take up this issue if noone else is working on it?
