### ISSUE TITLE
"Follow the instructions in the docs"  link in readme is broken

### ISSUE THREAD

**Issue by kanav-raina** [accordproject/cicero-template-library#319]
![broken_page](https://user-images.githubusercontent.com/29794748/75620922-1ef78400-5bb4-11ea-867d-219d83cb23c8.png)

![link](https://user-images.githubusercontent.com/29794748/75620949-8d3c4680-5bb4-11ea-8fda-2663d880a064.png)

Describe the bug
Link is broken in the README :
             https://docs.accordproject.org/docs/cicero-tutorial.html#creating-a-new-template

**Comment by kanav-raina** [comment]
Hi @jeromesimeon, @irmerk.
Kindly tell me what link address should I put in readme to correct this

**Comment by irmerk** [comment]
I believe https://docs.accordproject.org/docs/started-installation.html, @jeromesimeon?

**Comment by kanav-raina** [comment]
Should I open a PR @irmerk ?

**Comment by irmerk** [comment]
Sure that works @kanav-raina
