### ISSUE TITLE
Update nav logo to match models.accordproject.org

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-template-library#329]
The Accord Project nav logo on the template library page is inconsistent with the nav logo on models.accordproject.org , which uses the correct logo. 

![image](https://user-images.githubusercontent.com/40569793/78274306-0265a900-74de-11ea-981c-af38a952f846.png)

![image](https://user-images.githubusercontent.com/40569793/78274338-101b2e80-74de-11ea-9a34-e21d183ed815.png)

**Comment by arteevraina** [comment]
@Michael-Grover Can i take up this issue?

**Comment by Michael-Grover** [comment]
sure, thanks

**Comment by arteevraina** [comment]
@jeromesimeon Do i have to file a PR for this against the branch `cicero-0.20.0` ?

**Comment by jeromesimeon** [comment]
@arteevraina That one can go directly against master! (the logo was only on the branch, but this one is general styling).

**Comment by arteevraina** [comment]
@jeromesimeon Thanks, Sending a PR shortly :)
