### ISSUE TITLE
Template author styling changes

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-template-library#330]
https://github.com/accordproject/cicero-template-library/tree/cicero-0.20.10
In this branch we have added a line that says "Author: [logo] [author]" . I am requesting some minor styling changes. It currently looks like this:

![image](https://user-images.githubusercontent.com/40569793/78283552-ef59d580-74eb-11ea-9588-a0a843cd35a1.png)

We want it to look more like this:
![image](https://user-images.githubusercontent.com/40569793/78283647-17e1cf80-74ec-11ea-8ac5-63778b06b45f.png)

The changes are:
 - make the text 15pt
 - the author name on the right 600 weight

**Comment by arteevraina** [comment]
I will take up this one

**Comment by Michael-Grover** [comment]
cool thanks

**Comment by jeromesimeon** [comment]
Thanks @arteevraina Make sure to do a PR against the `cicero-0.20.10` branch.

**Comment by arteevraina** [comment]
Sure @jeromesimeon . I am currently setting up this project in my machine. I will be sending a PR for this soon.

**Comment by jeromesimeon** [comment]
Brilliant! Much appreciated.

**Comment by jeromesimeon** [comment]
The local build process is a little bit of a hack at the moment (you can test with `npm run build` but you should discard those changes after testing). Let me know if you have any trouble or question.

**Comment by arteevraina** [comment]
Sure!

**Comment by arteevraina** [comment]
I think this issue can be closed now @Michael-Grover @jeromesimeon
