### ISSUE TITLE
Accord Project logo not showing up in navbar

### ISSUE THREAD

**Issue by arteevraina** [accordproject/cicero-template-library#334]
**Screenshot**
![image](https://user-images.githubusercontent.com/43968121/78706702-233e5c00-792d-11ea-8dea-54ae2a91d37f.png)

**To Reproduce**
1. Run a build.
2. Load `build/index.html` in the browser manually.

**Expected behavior**
Logo should appear in the navbar instead of an `alternate text`

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: chrome

**Comment by arteevraina** [comment]
@Michael-Grover @jeromesimeon Can I work on this?

**Comment by jeromesimeon** [comment]
Sure @arteevraina 

That's only for local build. Correct?

**Comment by arteevraina** [comment]
@jeromesimeon Yes that's for local build.
