### ISSUE TITLE
Publish Compiled Archives

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#343]
# Feature Request 🛍️
A user should be able to download specific compiled archives in addition to or instead of the source code archive

## Use Case
**Specific**:

We are building a [Cicero Word Add-In](https://github.com/accordproject/cicero-word-add-in). Within the desktop version of Word, the embedded MS Edge browser which handles add-ins cannot seem to handle the action of `fromUrl` and `fromArchive`, which compiles Ergo into Javascript. Aside from utilizing web workers, accessing a pre-compiled archive from URL would be useful.

**Hypothetical**:

A user should be able to access compiled versions of the archive for their specific use case (ES6, WASM, etc.)

## Possible Solution
Adjust the build script for the templates to publish an ES6 compiled archive now, and further versions in the future. This will require strict semantic versioning.

## Context
Uncertain if Word is indeed using Edge for Add-Ins. Word online in the Edge browser works without issue. Also uncertain if web workers would solve the issue.

**Comment by jeromesimeon** [comment]
Done in #344
