### ISSUE TITLE
New Parser: Copyright License

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#346]
# Bug Report 🐛
Working with a micropublish of the new [Cicero parser](https://github.com/accordproject/cicero/tree/parserv2) and the [generated template](https://parserv2--templates-accordproject.netlify.app/archives/copyright-license@0.15.0.html), crashing on load

## Expected Behavior
Load without crashing

## Current Behavior
```sh
TypeError: Cannot read property 'slice' of undefined
    at index.esm.js:1
    at Oe (index.esm.js:1)
    at index.esm.js:1
    at renderWithHooks (react-dom.development.js:14803)
    at updateForwardRef (react-dom.development.js:16816)
    at beginWork (react-dom.development.js:18645)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
```

## Possible Solution
This may be in the rendering for the `ClauseComponent` in `web-components`

## Steps to Reproduce

1. Working off [this branch](https://github.com/irmerk/web-components/tree/irmerk/i69/formulae-ui)
2. Update latest micropublish of [Cicero (v0.21) Parser Branch](
https://github.com/accordproject/cicero/tree/parserv2) and [markdown-transform](https://github.com/accordproject/markdown-transform/tree/parserv2)
3. Load `https://parserv2--templates-accordproject.netlify.app/archives/copyright-license@0.15.0.cta` in storybook

### Desktop
 - OS: **macOS**
 - Browser: **Chrome**
 - Version: **0.21.0**
 - [Cicero (v0.21) Parser Branch](
https://github.com/accordproject/cicero/tree/parserv2)

**Comment by dselman** [comment]
Fixed in Storybook: https://github.com/accordproject/web-components/pull/168
