### ISSUE TITLE
Publish to templates.accordproject.org

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-template-library#53]
Create a build process that publishes the templates to templates.accordproject.org. 

- [x] Run unit tests for each template

- [x] We can build archives for each template (which will resolve all the external dependencies, so they load fast and are validated). 

- [ ] We can name each archive using the fqn of the template model, plus the version number from package.json.

- [ ] Save all versions of a valid template to cheap and reliable object/document storage

- [x] Generate an HTML overview page for each archive in object store, based on the README, package.json (compatible Cicero version) model info etc (edited)

- [x] We can link from the template HTML page to the model HTML page for external dependencies.

- [x] We can also publish an index.json file with metadata so that tools can quickly find templates based on metadata. (edited)

- [x] Add `Template.fromArchive(url)` to load a template from a URL

**Comment by jeromesimeon** [comment]
Quite a lot of this seems to be done (I checked those I believe are -- may need to be reviewed). A couple of things open:
- I don't believe we use the FQN for naming archives
- We don't have a dedicated storage, do we really need one?

**Comment by dselman** [comment]
Will close. We can open new issues as necessary.
